name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag discord_joining_notifier:$(date +%s)
      
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Tag image for Docker Hub
        run: docker image tag  discord_joining_notifier kolnol/discord_joining_notifier:$(date +%s)
      
      - name: Push to Docker Hub
        run: docekr push kolnol/discord_joining_notifier:$(date +%s)
